on: release
name: Release dabutvin/imgbot-compressimages
jobs:
  dockerRegistry:
    name: Docker Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.6
      with:
        name: dabutvin/imgbot-compressimages
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        dockerfile: Dockerfile.CompressImages
